# Generated by Django 5.1 on 2024-08-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
