# Generated by Django 5.1 on 2024-10-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_almacen_estado_alter_cliente_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_convenio', models.CharField(max_length=15, unique=True)),
                ('tipo_convenio', models.CharField(choices=[('MONTO', 'Aumento de Monto Máximo'), ('FECHA', 'Extensión de Fecha de Fin'), ('TEXTO', 'Cambio de Texto/Descripción')], max_length=10)),
                ('fecha_convenio', models.DateField()),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nueva_fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion_adicional', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='erp.contrato')),
            ],
        ),
    ]
