# Generated by Django 5.1 on 2024-08-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_contrato_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
