# Generated by Django 5.1 on 2024-08-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='presentacion',
            field=models.CharField(choices=[('TAMBOR', 'Tambor de 200 lts'), ('CUBETA', 'Cubeta de 19 lts'), ('BIDON', 'Bidón de 20 lts')], max_length=255),
        ),
    ]
