# Generated by Django 5.1 on 2024-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_convenios'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandoNaval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mando Naval',
                'verbose_name_plural': 'Mandos Navales',
            },
        ),
    ]
